version: '3'

services:
  server1:
    container_name: server1
    build: 
      context: ./node
    restart: on-failure
    ports:
      - "81:8080"
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - server1