version: '3'

services:
  db:
    image: mysql-db
    build: 
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - revprox   # Conectar a rede de proxy reverso
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 40s
      timeout: 30s
      retries: 3
  server1:
    container_name: server1
    image: node-app-th
    build: 
      context: ./node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - revprox   # Connect server1 to the revprox network
  nginx:
    container_name: nginx
    image: nginx-th
    build: 
      context: ./nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - server1
    networks:
      - revprox   # Connect nginx to the revprox network

  

networks:
  revprox:
    driver: bridge
